# Generated by Django 4.1.2 on 2023-02-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='date',
            new_name='created_at',
        ),
    ]
