# Generated by Django 4.1.2 on 2023-02-17 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_measurement_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='value',
            new_name='temperature',
        ),
    ]
